---
title: "SpermWhaleModelSelection"
author: "RC + LB"
date: "4/22/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(geepack)
library(splines2)
library(lubridate)
library(tidyverse)
library(car)
library(splines2)
library(ggplot2)
library(gridExtra)
library(zoo)
library(pracma)
library(mgcv)
library(SimDesign)
library(multitaper)
source("getPvalues.R")

data = data.frame(read.csv('J:/Chpt_3/ModelData/SpermWhale_masterDF.csv'))
lagID = 57
numClust = length(data$Pres)/(lagID-1)
if (numClust<length(data$Pres)){
  clustID = rep(1:ceiling(numClust),each=lagID)
  clustID = clustID[1:length(data$Pres)]
} else {
  clustID = 1:length(data$Pres)
}
data$GroupID = clustID

# Round presence to get Poisson dist
data$Pres = round(data$Pres)
```

# Plot pres vs. covars by year
```{r plot by year, fig.width=15, fig.height=10}

startDate = as.Date("2016-05-01",origin="1970-01-01")
endDate = as.Date("2019-04-30",origin="1970-01-01")
dateMarks = c(seq.Date(startDate,endDate,by="year"),endDate)
covarList = c("Chl0",
              "SSH0",
              "FSLE0")

profileDir = 'J:/Chpt_3/CovarTS'
profileList = dir(profileDir,pattern="Profiles_ES.Rdata",full.names=TRUE)
sites = c("HZ","NC","WC","HAT","GS","BS","JAX")
k=7

for (j in 1:length(sites)){
  
  siteInd = which(!is.na(str_match(data$Site,sites[j])))
  
  
  if (sum(data$Pres[siteInd]>0)>50){
    
    plotDF = data.frame(Pres = rollmean(data$Pres[siteInd],k=k,fill=NA),
                        Date = as.Date(rollmean(data$Date[siteInd],k=k,fill=NA),origin="1970-01-01"))
    
    for (m in 1:(length(dateMarks)-1)){ # for each year
      
      plotList = list()
      st = dateMarks[m]
      ed = dateMarks[m+1]
      
      plotList[['Pres']] = ggplot(plotDF,aes(x=Date) # plot presence in this year
      )+geom_line(aes(y=Pres)
      )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
      )+coord_cartesian(xlim=c(st,ed)
      )+ggtitle('Presence'
      )+labs(x=NULL,y=NULL
      )+theme(plot.margin=margin(c(0,43,0,0),unit="pt"))
      
      for (i in 1:length(covarList)){ # plot surface covars in this year
        
        plotDF$Covar = rollmean(data[[covarList[i]]][siteInd],k=k,fill=NA)
        
        plotList[[covarList[i]]] = ggplot(plotDF,aes(x=Date)
        )+geom_line(aes(y=Covar)
        )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
        )+coord_cartesian(xlim=c(st,ed)
        )+ggtitle(covarList[i]
        )+labs(x=NULL,y=NULL
        )+theme(plot.margin=margin(c(0,43,0,0),unit="pt"))
      }
      
      grid.arrange(grobs=plotList,ncol=1,nrow=length(covarList)+1,top=paste('Sperm Whales at',sites[j]))
      
    }
    
    
    for (i in 1:length(profileList)){ # for profiles of covars with multiple depth layers

          load(profileList[i])
      profileName = str_remove(str_remove(profileList[i],'_Profiles_ES.Rdata'),paste(profileDir,'/',sep=""))
      profileDF = data.frame(z=stack(data.frame(eval(parse(text=paste(sites[j],'Profile',sep="")))))[,1],
                             y=rep(depths,times=dim(eval(parse(text=paste(sites[j],'Profile',sep=""))))[2]),
                             x=rep(as.Date(masterData.Time,origin="1970-01-01"),each=length(depths)))
      
      for (m in 1:(length(dateMarks)-1)){
        st = dateMarks[m]
        ed = dateMarks[m+1]
        
        if (str_detect(profileName,"Asp")){
          
          plotList[['Pres']] = ggplot(plotDF,aes(x=Date) # plot presence in this year
          )+geom_line(aes(y=Pres)
          )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
          )+coord_cartesian(xlim=c(st,ed)
          )+ggtitle('Presence'
          )+labs(x=NULL,y=NULL
          )+theme(plot.margin=margin(c(0,0,0,0),unit="pt"))
          
          direction_labeller <- function(x){
            ifelse(x %% 45 == 0, c('E','NE','N','NW','W','SW','S','SE')[1+(as.integer(x/45) %% 8)], '')}
          my_colors=c("#2E22EA","#9E3DFB","#F86BE2","#FCCE7B","#C4E416","#4BBA0F","#447D87","#2C24E9")
          
          plotList[[profileName]] = ggplot(profileDF,aes(x=x,y=y,z=z) # plot profile for this year
          )+geom_contour_filled(
          )+scale_fill_manual(
            values=my_colors,
            guide=NULL
          )+coord_cartesian(xlim=c(st,ed)
          )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
          )+scale_y_reverse(
          )+ggtitle(profileName
          )+labs(x=NULL,y=NULL
          )+theme(plot.margin=margin(c(0,0,0,0),unit="pt"))
          
          hues_df = data.frame(degree = 0:359) %>%
            mutate(
              label=direction_labeller(degree+90 %% 360),
              colors = colorRampPalette(my_colors)(360))
          
          plotList[["ColorLegend"]] = ggplot(hues_df
          )+geom_rect(aes(ymin=3,
                          ymax=4,
                          xmin=degree-0.5,
                          xmax=degree+0.5,
                          color=colors,
                          fill=colors)
          )+coord_polar(direction=-1,
                        start=0
          )+scale_color_identity(
          )+scale_fill_identity(
          )+guides(fill=FALSE,color=FALSE
          )+theme_void(
          )+ylim(c(1,4.5)
          )+geom_text(aes(x=degree,
                          y=4.5,
                          label=label)) 
          
          grid.arrange(plotList$Pres,plotList[[profileName]],plotList[["ColorLegend"]],
                       ncol=12,nrow=3,top=paste('Sperm Whales at',sites[j]),layout_matrix=rbind(c(rep(1,11),NA),
                                                                                                   c(rep(2,11),NA),
                                                                                                   c(rep(2,11),3)))
          
        } else {
          
          plotList[['Pres']] = ggplot(plotDF,aes(x=Date) # plot presence in this year
          )+geom_line(aes(y=Pres)
          )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
          )+coord_cartesian(xlim=c(st,ed)
          )+ggtitle('Presence'
          )+labs(x=NULL,y=NULL
          # )+theme(plot.margin=margin(c(0,75,0,0),unit="pt"))
          )+theme(plot.margin=margin(c(0,40,0,0),unit="pt"))

          
          plotList[[profileName]] = ggplot(profileDF,aes(x=x,y=y,z=z) # plot profile for this year
          )+geom_contour_filled(
          )+coord_cartesian(xlim=c(st,ed)
          )+scale_x_continuous(breaks=c(seq.Date(from=st,to=ed,by="quarter"))
          )+scale_y_reverse(
          )+ggtitle(profileName
          )+labs(x=NULL,y=NULL
          # )+theme(plot.margin=margin(c(0,0,0,0),unit="pt"),
          #         legend.position="right",
          #         legend.title=element_text(size=0),
          #         legend.text=element_text(size=10),
          #         legend.key.size=unit(0.8,'lines'),
          #         legend.direction="vertical",
          #         legend.margin=margin(0))
          )+theme(plot.margin=margin(c(0,0,0,0),unit="pt"),
                  legend.position="right",
                  legend.title=element_text(size=0),
                  legend.text=element_text(size=7),
                  legend.key.size=unit(0.5,'lines'),
                  legend.direction="vertical",
                  legend.margin=margin(0))
          
          # png(file='J:/Chpt_3/FigsForLB/SBCD_v_Salin.png',width = 12, height = 9,units = "in",res=600)
          grid.arrange(plotList$Pres,plotList[[profileName]],
                       ncol=12,nrow=3,top=paste('Sperm Whales at',sites[j]),layout_matrix=rbind(c(rep(1,12)),
                                                                                                   c(rep(2,12)),
                                                                                                   c(rep(2,12))))
          # while (dev.cur()>1) {dev.off()}
        }
      }
    }
  }
}


```


# Plot scatterplots and histograms
```{r plotCovars}
# Fill in smoothVarList based on selection made above
smoothVarList = c("SSH0",
                  "Chl0",
                  "Sal0",
                  "Temp0",
                  "Sal700",
                  "Temp700",
                  "FSLE0",
                  "GSLat",
                  "Slope",
                  "Aspect")

pres = which(data$Pres>0)
presDF = data[pres,]
sites = c("HZ","NC","BC","NFC","GS","JAX")

for (i in 1:length(smoothVarList)){
  
  # Bootstrap the covar to produce a sample of the same size as pres
  refDist = sample(data[[smoothVarList[i]]],size=length(pres),replace=TRUE)
  
  # Compare empirical cumulative distribution functions with a Kolomogorov Smirnov test
  KS.out = ks.test(presDF[[smoothVarList[i]]],refDist,simulate.p.value=TRUE)
  
  # Plot presence bins across all data versus this covar
  edges = seq(min(data[[smoothVarList[i]]]),max(data[[smoothVarList[i]]]),length.out=50)
  binDiff = diff(edges[1:2])
  plotDF = data.frame(Obs=histc(refDist,edges=edges)$cnt/length(refDist),
                      Pres=histc(presDF[[smoothVarList[i]]],edges=edges)$cnt/dim(presDF)[1],
                      BinCenter=seq(min(data[[smoothVarList[i]]])+(0.5*binDiff),
                                    max(data[[smoothVarList[i]]])+(0.5*binDiff),
                                    by=binDiff))
  
  print(ggplot(plotDF
  )+geom_col(aes(x=BinCenter,y=Obs),
             fill='#bfbfbf',
             alpha=0.6
  )+geom_col(aes(x=BinCenter,y=Pres),
             fill='#66B2FF',
             alpha=0.5
  ) + labs(y="Normalized Counts",
           x=NULL,
           title=paste(smoothVarList[i],', p = ',as.character(KS.out$p.value),sep="")
  ) + theme_minimal())
  
  # print(ggplot(data
  # )+geom_point(aes(x=.data[[smoothVarList[i]]],y=Pres)
  # )+geom_smooth(aes(x=.data[[smoothVarList[i]]],y=Pres),
  #               method="loess"
  # )+labs(title=smoothVarList[i]))
  
  # Plot presence bins at each site versus this covar
  if (!str_detect(smoothVarList[i],"Slope") & !str_detect(smoothVarList[i],"Aspect")){
    for (j in 1:length(sites)){
      siteInd = which(!is.na(str_match(data$Site,sites[j])))
      if (length(siteInd)>7){
        print(ggplot(data[siteInd,]
        )+geom_point(aes(x=.data[[smoothVarList[i]]],y=Pres)
        )+geom_smooth(aes(x=.data[[smoothVarList[i]]],y=Pres),
                      method="loess"
        )+labs(title=paste(smoothVarList[i],'at',sites[j])))
      }
    }
  }
}


```